services:
  backend:
    depends_on:
      - database
    build: ./backend
    environment:
      APP_PORT: 8000
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: amazon_clone_test
    ports:
      - 8000:8000
    volumes:
      - .:/srv/backend
      - backend_node_modules:/srv/backend/node_modules
    healthcheck:
      test: [ "CMD-SHELL", "curl.sh || exit 0" ]
      interval: 10s
      timeout: 10s
      retries: 10
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  volumes:
    backend_node_modules:
