services:
    db:
        container_name: db
        image: "mysql:8.0.22"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3308:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=amazon_test
    backend:
        container_name: server
        depends_on:
            - db
        build: ./backend
        environment:
            - APP_PORT=8000
            - DB_HOST=db
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=root
            - DB_NAME=amazon_test
            - DB_HOST_TEST=db
            - DB_PORT_TEST=3306
            - DB_USER_TEST=root
            - DB_PASSWORD_TEST=root
            - DB_NAME_TEST=amazon_clone_test
            - CLIENT_URL=http://localhost:3000
            - ACCESS_JWT_SECRET=vYDvp5cOC5D3ixW2PH0lVb1kjnvRBjyZOHehOd9zeANe1h4uY13jk93WyCAbT92
            - ACCESS_JWT_EXPIRESIN=60s
            - REFRESH_JWT_SECRET=4VK07QhOIWXeIMJisrpycdKOJT1Jf7n4bgiJsCjzpllFDTvU2MdTWtRcS1cHGiv
            - REFRESH_JWT_EXPIRESIN=1h
            - REFRESH_JWT_COOKIE_MAXAGE=3600000
            - REFRESH_JWT_COOKIE_SECURE=false
        ports:
            - "8000:8000"
        command: 'bash -c "chmod u+x ./scripts/wait-for-it.sh && ./scripts/wait-for-it.sh db:3306 && npm run migrate:test && npm run test"'
    frontend:
        container_name: client
        build: ./frontend
        command: 'bash -c "npm run test"'
