services:
  backend:
    depends_on:
      - database
    build: ./backend
    environment:
      APP_PORT: 8000
      NODE_ENV: test
      DB_HOST_TEST: database
      DB_USER_TEST: root
      DB_PASSWORD_TEST: root
      DB_NAME_TEST: amazon_clone_test
    ports:
      - 8000:8000
    healthcheck:
      test: [ "CMD-SHELL", "curl.sh || exit 0" ]
      interval: 10s
      timeout: 10s
      retries: 10
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
